# Generated by Django 3.2.6 on 2022-07-24 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0002_alter_ponto_data_hora_saida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ponto',
            name='data_hora_entrada',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='data_hora_saida',
        ),
        migrations.AddField(
            model_name='ponto',
            name='data_entrada',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ponto',
            name='data_saida',
            field=models.DateField(blank=True, default=datetime.datetime.now, null=True),
        ),
        migrations.AddField(
            model_name='ponto',
            name='hora_entrada',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ponto',
            name='hora_saida',
            field=models.TimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
