# Generated by Django 3.2.6 on 2022-07-30 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0003_auto_20220724_1956'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='data_entrada',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='ponto',
            old_name='hora_entrada',
            new_name='hora',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='data_saida',
        ),
        migrations.RemoveField(
            model_name='ponto',
            name='hora_saida',
        ),
        migrations.AddField(
            model_name='ponto',
            name='tipo',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
