# Generated by Django 3.2.6 on 2022-08-20 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0004_auto_20220730_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='ponto',
            name='validacao',
            field=models.BooleanField(default=False),
        ),
    ]
