# Generated by Django 3.2.6 on 2022-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ponto', '0005_ponto_validacao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ponto',
            old_name='validacao',
            new_name='validacao_definitiva',
        ),
        migrations.AddField(
            model_name='ponto',
            name='validacao_provisoria',
            field=models.BooleanField(default=False),
        ),
    ]
