# Generated by Django 3.2.6 on 2022-07-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('matricula', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=40)),
                ('cpf', models.CharField(max_length=14)),
                ('telefone', models.CharField(blank=True, max_length=40)),
                ('email', models.CharField(blank=True, max_length=40)),
                ('endereco', models.CharField(max_length=100)),
                ('dt_nascimento', models.CharField(max_length=10)),
                ('dt_admissao', models.DateField(auto_now_add=True)),
                ('cargo', models.CharField(max_length=100)),
                ('salario', models.FloatField()),
            ],
            options={
                'verbose_name': 'Funcionario',
                'verbose_name_plural': 'Funcionarios',
                'ordering': ['matricula'],
            },
        ),
    ]
