# Generated by Django 3.2.6 on 2022-07-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='matricula',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
