# Generated by Django 3.2.6 on 2022-07-17 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
        ('cargo', '0001_initial'),
        ('funcionario', '0002_alter_funcionario_matricula'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='cargo',
        ),
        migrations.RemoveField(
            model_name='funcionario',
            name='salario',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_cargo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='cargo.cargo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='funcionario',
            name='id_supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.supervisor'),
            preserve_default=False,
        ),
    ]
