# Generated by Django 3.2.6 on 2022-07-17 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0004_alter_funcionario_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='funcionario',
            name='id_supervisor',
        ),
    ]
