# Generated by Django 3.2.6 on 2022-07-17 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0004_remove_supervisor_matricula'),
        ('funcionario', '0005_remove_funcionario_id_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='id_supervisor',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='supervisor.supervisor'),
            preserve_default=False,
        ),
    ]
