# Generated by Django 3.2.6 on 2022-07-17 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0007_auto_20220717_1818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='funcionario',
            old_name='nome',
            new_name='primeiro_nome',
        ),
        migrations.AddField(
            model_name='funcionario',
            name='ultimo_nome',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
