# Generated by Django 3.2.6 on 2022-07-23 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0009_auto_20220723_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dt_admissao',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dt_demissao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dt_nascimento',
            field=models.DateField(),
        ),
    ]
