# Generated by Django 3.2.6 on 2022-07-23 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0010_auto_20220723_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='dt_demissao',
            field=models.DateField(blank=True),
        ),
    ]
