# Generated by Django 3.2.6 on 2022-07-24 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0012_alter_funcionario_dt_demissao'),
    ]

    operations = [
        migrations.CreateModel(
            name='SenhaProvisoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=10)),
                ('senha_provisoria', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativa')),
            ],
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
    ]
