# Generated by Django 3.2.6 on 2022-07-17 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='nome',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
