# Generated by Django 3.2.6 on 2022-07-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supervisor', '0003_auto_20220717_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='matricula',
        ),
    ]
