# Generated by Django 3.2.6 on 2022-07-17 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionario', '0007_auto_20220717_1818'),
        ('supervisor', '0004_remove_supervisor_matricula'),
    ]

    operations = [
        migrations.AddField(
            model_name='supervisor',
            name='funci',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='funcionario.funcionario'),
            preserve_default=False,
        ),
    ]
